<div style="text-align: center;">
  <img src="https://github.com/Hack-io-Data/Imagenes/blob/main/01-LogosHackio/logo_naranja@4x.png?raw=true" alt="esquema" />
</div>

In [2]:
import os

In [4]:
datos = os.listdir()
datos

['laboratorio-modulo2-leccion01-numpy.ipynb',
 'laboratorio-modulo2-leccion05-limpieza.ipynb',
 'laboratorio-modulo2-leccion04-visualizacion.ipynb',
 'laboratorio-modulo2-leccion03-groupby.ipynb',
 'laboratorio-modulo2-leccion02-eda-union.ipynb',
 'laboratorio-modulo2-leccion03-filtrado.ipynb']

In [ ]:
diccioanrio_df = {diccioanrio_df[re.findall("\d{4}", i)[0]] : pd.read_csv(f"..dato/{i}") for i in datos}

diccioanrio_df = {}
for i in datos:
    df = pd.read_csv(i)
    diccioanrio_df[i.spl]


In [1]:
import numpy as np 

for i in datos
# Laboratorio de NumPy

#### Ejercicio 1 - Crea un array de 1D con los números del 0 al 9.

In [2]:
array1 = np.arange(10)
print("Array 1D:", array1)

Array 1D: [0 1 2 3 4 5 6 7 8 9]


#### Ejercicio 2 - Convierte un array 1D en un array 2D con 2 filas y 5 columnas.

In [7]:
# podemos transformarlo porque tenemos el mismo numero de valores (10)
array2 = array1.reshape(2,5)
print(f"Este es el array 1D: {array1}")
print(f"Este es el array convertido a 2D, con 2 filas y 5 columnas: {array2}")

Este es el array 1D: [0 1 2 3 4 5 6 7 8 9]
Este es el array convertido a 2D, con 2 filas y 5 columnas: [[0 1 2 3 4]
 [5 6 7 8 9]]


#### Ejercicio 3 - Encuentra los índices de los elementos con valor distinto de 0 en el siguiente array: [0, 2, 0, 3, 0, 4, 0].

In [8]:
array3 = np.array([0,2,0,3,0,4,0])
indices = [i for i , value in enumerate(array3) if value !=0]

print(f"Este es el array original:{array3}")
print(f"Estos son los indices de elementos distintos de 0: {indices}")

Este es el array original:[0 2 0 3 0 4 0]
Estos son los indices de elementos distintos de 0: [1, 3, 5]


#### Ejercicio 4 - Crea un array 3x3 con valores aleatorios entre 0 y 1.

In [ ]:
#con np.random.rand reproducimos valores aleatorios, con np.random.randint valores enteros aleatorios 
array_random = np.random.rand(3,3)

print(f"Este es un array random con valores aleatorios entre 0 y 1:{array_random}")

Este es un array random con valores aleatorios entre 0 y 1:[[0.54782384 0.73093273 0.60954297]
 [0.18812286 0.39825672 0.0246486 ]
 [0.356278   0.82284931 0.38353228]]


#### Ejercicio 5 - Crea un array de 10 números aleatorios y encuentra el valor máximo y mínimo.

In [11]:
# generamos un array con 10 numeros aleatorios ( cada vez que ejecutemos el código los valores cambiarán)
array_random2 = np.random.rand(10)

#creamos las variables de valor maximo y minimo con np.max y np.min 
valor_max = np.max(array_random2)
valor_min = np.min(array_random2)

# mostramos resultado 
print(f"Este es el array random generado: {array_random2}")
print(f"Este es el valor maximo del array: {valor_max}")
print(f"Este es el valor minimo del array: {valor_min}")

Este es el array random generado: [0.46049906 0.35496278 0.80503454 0.14595406 0.17701628 0.58003111
 0.20253164 0.71953962 0.17166409 0.16656927]
Este es el valor maximo del array: 0.8050345435960818
Este es el valor minimo del array: 0.14595406071180872


#### Ejercicio 6 - Crea un array de una dimensión e inviértelo. 

In [ ]:
array4 = np.arange(10)

#desglosamos el array y empezamos metodo [start:stop:step] en donde start cogemos todos los numeros del array, stop recorremos de principio a fin y step -1 para que empiece en orden inverso de los indices.
array_invertido = array4[::-1]


print(f"Este el es el array original:{array4}")
print(f"Este es el array invertido: {array_invertido}")

Este el es el array original:[0 1 2 3 4 5 6 7 8 9]
Este es el array invertido: [9 8 7 6 5 4 3 2 1 0]



#### Ejercicio 6 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Selecciona el primer `15` del array.

- Selecciona todos los elementos del primer array. 

- Selecciona la última fila del último array


In [13]:
array_tridimensional = np.arange(1,25)
array_tridimensional = array_tridimensional.reshape(2,3,4)

print(array_tridimensional)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]



#### Ejercicio 7 - Genera un array tridimensional de dimensiones (3, 2, 5) con valores enteros del 1 al 30.

- Selecciona el subarray que contiene los dos primeros elementos de cada fila del primer array.

- Selecciona el subarray que contiene todas las filas de los dos últimos arrays.


In [16]:
array_tridimensional2 = np.arange(1,31)
array_tridimensional2 = array_tridimensional2.reshape(3,2,5)

print(array_tridimensional2)

sub_array1 = array_tridimensional2[0, :, 2]
print(f"Este es el subarray que contiene los dos primeros elementos de cada fila del primer array:{sub_array1}")

sub_array2 = array_tridimensional2[1:, :, :]
print(f"Este es el segundo subarray que contiene todas las filas de los dos ultimos arrays:{sub_array2}")



[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]]]
Este es el subarray que contiene los dos primeros elementos de cada fila del primer array:[3 8]
Este es el segundo subarray que contiene todas las filas de los dos ultimos arrays:[[[11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]]]


#### Ejercicio 8 - Genera un array tridimensional de dimensiones (4, 3, 2) con valores enteros del 1 al 24.

- Cambia todos los elementos de la segunda fila del segundo array por `0`.

- Cambia todos los valores del último array a `-1`.


In [17]:
array_tridimensional3 = np.arange(1,25).reshape(4,3,2)
print(f"Este es el array tridimensional original: {array_tridimensional3}")

array_tridimensional3[1,1, :] = 0 
array_tridimensional3[3,:,:] = -1

print(f"Este el array con los cambios: {array_tridimensional3}")

Este es el array tridimensional original: [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]

 [[19 20]
  [21 22]
  [23 24]]]
Este el array con los cambios: [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 0  0]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]

 [[-1 -1]
  [-1 -1]
  [-1 -1]]]



#### Ejercicio 9 - Genera un array tridimensional de dimensiones (2, 4, 3) con valores enteros del -10 al 13.

- Selecciona todos los elementos mayores a `5`.

- Reemplaza todos los elementos negativos por `0`.


In [21]:
array_tridimensional4 = np.arange(-10,14).reshape(2,4,3)
print(f"Este el array tridimensional original :{array_tridimensional4}")

elementos_mayores_a_5 = array_tridimensional4 > 5
print(f"Estos son los elementos mayores a 5 en el array: {elementos_mayores_a_5}")

array_tridimensional4[array_tridimensional < 0] = 0 
print(f"Este es el array despues de camnbiar los elementos negativos por 0: {array_tridimensional4}")


Este el array tridimensional original :[[[-10  -9  -8]
  [ -7  -6  -5]
  [ -4  -3  -2]
  [ -1   0   1]]

 [[  2   3   4]
  [  5   6   7]
  [  8   9  10]
  [ 11  12  13]]]
Estos son los elementos mayores a 5 en el array: [[[False False False]
  [False False False]
  [False False False]
  [False False False]]

 [[False False False]
  [False  True  True]
  [ True  True  True]
  [ True  True  True]]]


IndexError: boolean index did not match indexed array along axis 1; size of axis is 4 but size of corresponding boolean axis is 3

#### Ejercicio 10 - Genera un array tridimensional de dimensiones (3, 3, 3) con valores enteros del 1 al 27.

- Selecciona el subarray del segundo array que contenga solo las dos primeras columnas.

- Selecciona todos los elementos del tercer array que sean mayores que `20`.


In [22]:
array_tridimensiona5 = np.arange(1,28).reshape(3,3,3)
print(array_tridimensiona5)

sub_array3 = array_tridimensiona5[1,:,:2]
print(f"Este es el primer subarray : {sub_array3}")

sub_array4 = array_tridimensiona5[2,array_tridimensiona5[2] > 20]
print(f"Este es el segundo subarray con elementos mayores a 20: {sub_array4}")

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
Este es el primer subarray : [[10 11]
 [13 14]
 [16 17]]
Este es el segundo subarray con elementos mayores a 20: [21 22 23 24 25 26 27]


#### Ejercicio 11 - Crea un array de 10 números aleatorios y reemplaza los valores máximos y mínimos por 0.

In [29]:
array_aleatorio = np.arange(11)
print(f"Este el array original: {array_aleatorio}")

valor_maximo = np.max(array_aleatorio)
valor_minimo = np.min(array_aleatorio)

array_aleatorio [array_aleatorio == valor_maximo] = 0 
array_aleatorio [array_aleatorio == valor_minimo] = 0
print(f"Este es el array definitvo con los valores sustituidos :{array_aleatorio}")

Este el array original: [ 0  1  2  3  4  5  6  7  8  9 10]
Este es el array definitvo con los valores sustituidos :[0 1 2 3 4 5 6 7 8 9 0]


#### Ejercicio 12 - Genera un array de 15 números aleatorios enteros entre 1 y 100 y reordénalo en orden ascendente.

In [31]:
array_aleatorio2 = np.random.randint(1,101, size=15)
print(f"Este es el array original: {array_aleatorio2}")

array_ascendente = np.sort(array_aleatorio2)
print(f"Este es el array con orden ascendente : {array_ascendente}")

Este es el array original: [51 11 40 43 25 93 91 71 84 82 34 88 17 95 35]
Este es el array con orden ascendente : [11 17 25 34 35 40 43 51 71 82 84 88 91 93 95]


#### Ejercicio 11 - Calcula la suma de los elementos a lo largo de las filas y columnas en una matriz 4x4.

In [32]:
matriz = np.random.randint(1,11, size=(4,4))
print(f"Esta es la matriz 4x4 : {matriz}")

suma_filas = []
for fila in matriz : 
    suma_filas.append(sum(fila))

    suma_columnas = []
    for col in range(matriz.shape[1]): 
        suma_columnas.append(sum(matriz[:,col]))

print(f"Esta es la suma de las filas:{suma_filas}")
print(f"Esta es la suma de las columnas:{suma_columnas}")

Esta es la matriz 4x4 : [[ 1  4  3  1]
 [ 8 10  1  5]
 [ 8  3  6  7]
 [ 2  5 10  1]]
Esta es la suma de las filas:[np.int64(9), np.int64(24), np.int64(24), np.int64(18)]
Esta es la suma de las columnas:[np.int64(19), np.int64(22), np.int64(20), np.int64(14)]


#### Ejercicio 12 - Crea una matriz de 5x5 con valores en el borde igual a 1 y en el interior igual a 0.

#### Ejercicio 13 - Calcula la media y la desviación estándar de un array de 10 números aleatorios.

#### Ejercicio 14 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Transpón el array para intercambiar los ejes de la forma (2, 3, 4) a (4, 3, 2).

- Observa cómo cambian las posiciones de los elementos y sus índices después de la transposición. Explica en una celda de markdown que es lo que ha pasado. 


#### Ejercicio 15 - Genera un array tridimensional de dimensiones (3, 4, 2) con valores enteros del 1 al 24.

- Transpón el array para intercambiar el primer y segundo eje, de manera que la nueva forma del array sea (4, 3, 2).


#### Ejercicio 16 - Genera un array tridimensional de dimensiones (3, 2, 4) con valores enteros del 1 al 24.

- Realiza una rotación completa de los ejes para convertir la forma original (3, 2, 4) en (4, 3, 2).


#### Ejercicio 17 - Manipulación de Arrays en 3D

- Crea un array tridimensional con dimensiones (3, 4, 5) cuyos elementos sean números enteros aleatorios entre -10 y 10.

- Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Luego, reemplaza los valores de la matriz vacía basada en los valores del primer array bajo las siguientes condiciones:

   - Si el valor es igual a la mediana, se reemplaza por `"M"`.

   - Si el valor es mayor que la mediana, se reemplaza por `"X"`.

   - Si el valor es menor que la mediana, se reemplaza por `"Y"`.

   - Si el valor es igual al máximo, se reemplaza por `"MAX"`.

   - Si el valor es igual al mínimo, se reemplaza por `"MIN"`.


#### Ejercicio 18 - Verificación de Filas y Columnas Iguales

Crea un array bidimensional de dimensiones 4x4, escribe un código para determinar si alguna fila es exactamente igual a alguna columna.

**Reglas:**

- No puedes usar funciones predefinidas de NumPy para comparar filas y columnas (`np.array_equal`, etc.).

- Debes resolverlo con estructuras básicas de Python (bucles, condicionales, etc.).

- Debes revisar si hay al menos una fila que coincida exactamente con alguna columna.

**Pistas**:

- Puedes recorrer cada fila y cada columna de la matriz usando bucles.

- Para comparar una fila con una columna, puedes hacerlo elemento por elemento.